<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Shared\SmartHome.Shared\SmartHome.Shared.csproj" />
    <ProjectReference Include="..\..\Repository\SmartHome.Slices.Devices.Repository\SmartHome.Slices.Devices.Repository.csproj" />
  </ItemGroup>

</Project>
