@SmartHome.Api_HostAddress = http://localhost:5241

GET {{SmartHome.Api_HostAddress}}/api/devices/
Accept: application/json

###


GET {{SmartHome.Api_HostAddress}}/api/devices/28888885-001
Accept: application/json

###


GET {{SmartHome.Api_HostAddress}}/api/devices/search?name=3rd
Accept: application/json

###


POST {{SmartHome.Api_HostAddress}}/api/devices/
Content-Type: application/json
{
  "id": "3",
  "name": "TestDevice",
  "type": "Camera",
  "ipAddress": "1",
  "active": true
}

###

PATCH {{SmartHome.Api_HostAddress}}/api/devices/status/20250826-002/false
Accept: application/json

###